apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-sample-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-sample-app
    spec:
      containers:
      - name: app-container
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        imagePullPolicy: Always # Use IfNotPresent for prod
        ports:
        - containerPort: 80
